project:
  type: website
  output-dir: docs

website:
  title: "Flu Shot Prediction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_description.qmd
        text: Data Description
      - href: eda.qmd
        text: EDA
